### ISSUE TITLE
LANL experiment event filtering in split.py

### ISSUE THREAD

**Issue by TomoshibiAkira** [iHeartGraph/Euler#5]
Hi! First, thank you for publishing the code!

I noticed that during LANL dataset preprocessing, the code in `split.py` [(L107)](https://github.com/iHeartGraph/Euler/blob/483ce8fb69166804d41304c6b2e08514d6f7d02b/lanl_experiments/loaders/split.py#L107) only collects event for NTLM and filters out all other events.

There are ~50M recorded NTLM events (~5% of the original file). In comparsion, Kerberos has ~300M.
Is this filtering intentional? If so, why do you specifically choose NTLM events?

**Comment by zazyzaya** [comment]
Hi! 
Yes, this is intentional. The Kerberos events are very noisy; most edges are from users to the ticket-granting server rather than directly between users and machines. This makes relations more indirect. It's to cut down the amount of data we process, and cut down the amount of "administrative" edges (e.g. edges to the KDC).
